### ISSUE TITLE
Inclusion of a strict molecular clock in BEAST

### ISSUE THREAD

**Issue by waughsh** [arjun-1/BEASTvntr#2]
I'm trying to determine the feasibility of including a strict molecular clock in my BEAST analysis. Right now, I don't see anything on your package to include a temporal (year) aspect within. Is this a possibility with this type of analysis? Or do microsatellite loci not have sufficient information to estimate rates among branches?

**Comment by arjun-1** [comment]
Hi there,
I am not sure what the source of your problem is. BEASTvntr poses no restrictions on estimating the clock rate (or substitution rate). Just specify tip dates or use a prior on the MRCA (this is all described in the beast2 [book](http://www.beast2.org/book/)).
Perhaps you are confused by the grayed-out box to estimate the Clock rate in the Clock Model panel? This is because Beast2 automatically sets the clock rate. If you untoggle **Mode > Automatic set clock rate**, you can estimate the clock rate again.

If you specify where exactly you are expecting to see an option in Beauti, where you are currently not seeing one, I can be of more help.
